### ISSUE TITLE
包的依赖关系出现冲突

### ISSUE THREAD

**Issue by xunzhang123** [Lucius-lsr/AdapterGNN#1]
您好，我在使用conda env create -f environment.yml命令创建虚拟环境时，提示 cryptography 和 openssl 包的依赖关系时出现了冲突。例如，cryptography-36.0.0-py39h9ce1e76_0 要求安装的 openssl 版本必须小于1.1.2a，而另一个包 python-3.9.10-hc74c709_2_cpython 要求安装的 openssl 版本必须大于等于3.0.0且小于4.0a0。由于这两个要求是矛盾的，导致了无法解决环境依赖关系。
如何解决这个问题？

**Comment by Lucius-lsr** [comment]
我也重新试了一下用yml安装确实失败了，应该是很多包的历史版本不再维护了
我直接按照readme里面要求的版本手动安装成功了，已经更新了readme
但是我的cuda是11，不确定cuda 12是否兼容torch 1.10.*，所以也不确定是否在任何环境下都能顺利配置，只能保证按照readme的环境配置程序可以顺利运行
