### ISSUE TITLE
预训练模型和当前定义的模型结构存在差异：运行reproduce.sh时，graphcl_80.pth和simgrace_80.pth编译不通过

### ISSUE THREAD

**Issue by xunzhang123** [Lucius-lsr/AdapterGNN#2]
您好，报错信息如下，该如何解决：Traceback (most recent call last):
  File "/data/Adapter/AdapterGNN-main/chem/finetune.py", line 228, in <module>
    acc = main(runseed, dataset)
  File "/data/Adapter/AdapterGNN-main/chem/finetune.py", line 173, in main
    model.from_pretrained(args.input_model_file)
  File "/data/Adapter/AdapterGNN-main/chem/adapterGNN.py", line 397, in from_pretrained
    self.gnn.load_state_dict(torch.load(model_file), strict=False)
  File "/data/anaconda3/envs/adaptergnn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GNN:
        size mismatch for gnns.0.mlp.0.weight: copying a param with shape torch.Size([600, 600]) from checkpoint, the shape in current model is torch.Size([600, 300]).
        size mismatch for gnns.1.mlp.0.weight: copying a param with shape torch.Size([600, 600]) from checkpoint, the shape in current model is torch.Size([600, 300]).
        size mismatch for gnns.2.mlp.0.weight: copying a param with shape torch.Size([600, 600]) from checkpoint, the shape in current model is torch.Size([600, 300]).
        size mismatch for gnns.3.mlp.0.weight: copying a param with shape torch.Size([600, 600]) from checkpoint, the shape in current model is torch.Size([600, 300]).
        size mismatch for gnns.4.mlp.0.weight: copying a param with shape torch.Size([600, 600]) from checkpoint, the shape in current model is torch.Size([600, 300]).
Traceback (most recent call last):
  File "/data/Adapter/AdapterGNN-main/chem/finetune.py", line 228, in <module>
    acc = main(runseed, dataset)
  File "/data/Adapter/AdapterGNN-main/chem/finetune.py", line 173, in main
    model.from_pretrained(args.input_model_file)
  File "/data/Adapter/AdapterGNN-main/chem/adapterGNN.py", line 397, in from_pretrained
    self.gnn.load_state_dict(torch.load(model_file), strict=False)
  File "/data/anaconda3/envs/adaptergnn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GNN:
        size mismatch for gnns.0.mlp.0.weight: copying a param with shape torch.Size([600, 600]) from checkpoint, the shape in current model is torch.Size([600, 300]).
        size mismatch for gnns.1.mlp.0.weight: copying a param with shape torch.Size([600, 600]) from checkpoint, the shape in current model is torch.Size([600, 300]).
        size mismatch for gnns.2.mlp.0.weight: copying a param with shape torch.Size([600, 600]) from checkpoint, the shape in current model is torch.Size([600, 300]).
        size mismatch for gnns.3.mlp.0.weight: copying a param with shape torch.Size([600, 600]) from checkpoint, the shape in current model is torch.Size([600, 300]).
        size mismatch for gnns.4.mlp.0.weight: copying a param with shape torch.Size([600, 600]) from checkpoint, the shape in current model is torch.Size([600, 300]).

**Comment by Lucius-lsr** [comment]
你应该是把bio实验的checkpoint用到chem实验里面了，因为bio的mlp是600x600的，chem是600x300的。simgrace的chem实验的checkpoint用这个：https://github.com/mpanpan/SimGRACE/blob/main/transfer_learning/chem/models_simgrace/simgrace_80.pth

**Comment by xunzhang123** [comment]
感谢解答！
