### ISSUE TITLE
仅需调整5%的参数是如何计算出来的？

### ISSUE THREAD

**Issue by xunzhang123** [Lucius-lsr/AdapterGNN#3]
我在finetune.py文件的“optimizer = optim.Adam(model_param_group, lr=args.lr, weight_decay=args.decay)”代码后面添加：如下代码块，但是输出需要调整的参数为180多万个，没有得到文章中说的5%左右的参数，是我计算的不对吗？
def count_parameters(model):
        return sum(p.numel() for p in model.parameters() if p.requires_grad)

    total_params = count_parameters(model)
    print(f"Total trainable parameters: {total_params}")

**Comment by xunzhang123** [comment]
如果方便的话，还想请您给我指出一下代码中是如何冻结模型参数，仅微调adapter的，万分感谢！

**Comment by Lucius-lsr** [comment]
感谢提醒，finetune.py的182-192行，只把允许微调的参数纳入进model_param_group了。其它参数应该也计算了梯度，只是没更新。这里的实现没考虑内存优化，确实可以改进

# AdapterGNN
if type(model) is AdapterGNN_graphpred:
    model_param_group = []
    model_param_group.append({"params": model.gnn.prompts.parameters(), "lr": args.lr})
    model_param_group.append({"params": model.gnn.gating_parameter, "lr": args.lr})
    for name, p in model.gnn.named_parameters():
        if name.startswith('batch_norms'):
            model_param_group.append({"params": p})
        if 'mlp' in name and name.endswith('bias'):
            model_param_group.append({"params": p})
    model_param_group.append({"params": model.graph_pred_linear.parameters(), "lr": args.lr})

**Comment by xunzhang123** [comment]
好的非常感谢！
